# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(326, 263)
        Form.setMaximumSize(QtCore.QSize(500, 500))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 80, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 120, 72, 15))
        self.label_2.setObjectName("label_2")
        self.password_input = QtWidgets.QLineEdit(Form)
        self.password_input.setGeometry(QtCore.QRect(160, 120, 113, 21))
        self.password_input.setObjectName("password_input")
        self.user_comboBox = QtWidgets.QComboBox(Form)
        self.user_comboBox.setGeometry(QtCore.QRect(160, 80, 111, 22))
        self.user_comboBox.setObjectName("user_comboBox")
        self.user_comboBox.addItem("")
        self.user_comboBox.addItem("")
        self.user_comboBox.addItem("")
        self.user_comboBox.addItem("")
        self.login_button = QtWidgets.QPushButton(Form)
        self.login_button.setGeometry(QtCore.QRect(60, 160, 211, 28))
        self.login_button.setObjectName("login_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Retrieval Tool"))
        self.label.setText(_translate("Form", "用户角色"))
        self.label_2.setText(_translate("Form", "密   码"))
        self.user_comboBox.setItemText(0, _translate("Form", "游客"))
        self.user_comboBox.setItemText(1, _translate("Form", "老师"))
        self.user_comboBox.setItemText(2, _translate("Form", "学生"))
        self.user_comboBox.setItemText(3, _translate("Form", "家长"))
        self.login_button.setText(_translate("Form", "登录"))
