# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1110, 616)
        self.table_show = QtWidgets.QTableView(Form)
        self.table_show.setGeometry(QtCore.QRect(20, 60, 1061, 511))
        self.table_show.setObjectName("table_show")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 141, 16))
        self.label.setObjectName("label")
        self.query_input = QtWidgets.QLineEdit(Form)
        self.query_input.setGeometry(QtCore.QRect(180, 20, 471, 21))
        self.query_input.setObjectName("query_input")
        self.web_button = QtWidgets.QPushButton(Form)
        self.web_button.setGeometry(QtCore.QRect(690, 20, 131, 28))
        self.web_button.setObjectName("web_button")
        self.file_button = QtWidgets.QPushButton(Form)
        self.file_button.setGeometry(QtCore.QRect(830, 20, 131, 28))
        self.file_button.setObjectName("file_button")
        self.return_button = QtWidgets.QPushButton(Form)
        self.return_button.setGeometry(QtCore.QRect(1010, 20, 51, 28))
        self.return_button.setObjectName("return_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Retrival Tool"))
        self.label.setText(_translate("Form", "请输入待检索内容："))
        self.web_button.setText(_translate("Form", "网页数据查询"))
        self.file_button.setText(_translate("Form", "相关文档查询"))
        self.return_button.setText(_translate("Form", "返回"))
